version: '3'
services:
  mysql:
    image: mysql:8
    container_name: peer_backend
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peer
  redis:
    image: redis:alpine
    container_name: peer_redis
    ports:
      - "16379:6379"
    labels:
      - "name=redis"
      - "mode=standalone"