spring:
  redis:
    host: 10.0.1.74
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # swagger

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.1.33:3306/peer?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root

  security:
    oauth2:
      client:
        registration:
          ft:
            client-id: u-s4t2ud-878c3954e7ce03154571d30d7499ec4e8880ccdba220c8a2c8cf4a4b71ea1d51
            client-secret: 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
            client-name: ft
            scope:
              - public
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/ft
          google:
            client-id: 889460259597-ggticgamsbbn2p930vaur19sqobqmus8.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          github:
            client-id: 6805bbb9c0e8503d21f8
            client-secret: b691ccc384cee514de82c241e1c39cacd5f457fe
            scope:
              - user
        provider:
          ft:
            authorization-uri: https://api.intra.42.fr/oauth/authorize
            token-uri: https://api.intra.42.fr/oauth/token
            user-info-uri: https://api.intra.42.fr/v2/me
            user-name-attribute: login
            jwk-set-uri: https://api.intra.42.fr/oauth/token_keys

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        default_batch_fetch_size: 1000

  mail:
    host: smtp.gmail.com
    port: 587
    username: juhyelee134@gmail.com
    password: qstrpngbbmmgnyeg
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도
          timeout: 5000 # socket read timeout
          starttls:
            enable: true # Start TLS 활성화
  data:
    mongodb:
      host: 10.0.1.43
      port: 27017
      authentication-database: admin
      database: peer
      username: peer
      password: peer

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always


jwt:
  token:
    secret: "secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey"
    validity-in-seconds: 10800000
    validity-in-seconds-refresh: 604800000

app:
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/login/oauth2/code/42
      - http://localhost:8080/login/oauth2/code/google

logging:
  config: resources/log4j2/log4j2.xml

url:
  front-server-url: http://133.186.153.113
  front-local-url: http://localhost:3000
  dev-domain-url: http://www.peer-test.co.kr


custom:
  filePath: "/Users"
